### ISSUE TITLE
Add more items to "how to help" list

### ISSUE THREAD

**Issue by brittag** [openhatch/oh-campus-foss#9]
The "How to help out" list should invite interested people to join the OSCTC-planning mailing list, and possibly also suggest to them to follow OpenHatch on Twitter & join the IRC channel.

**Comment by sri-teja** [comment]
The information you had suggested to mentioned was already mentioned in "Get Started". Let me know if the same should be there in "How to Help out" list also.

**Comment by shaunagm** [comment]
To be addressed via this issue: https://github.com/openhatch/open-source-comes-to-campus/issues/114
